export interface IMethodAnalysis {
  IdMethodAnalysis: number
  Codigo : string;
  ProcesoManufact : string;
  IdProducto : number;
  TipoProducto : string;
  Operacion : string;
  IdDataMachine : number;
  DataMachine : string;
  Stitch : string;
  Delay :  number;
  Personal : number;
  Fatigue : number;
  Rpm: number;
  Sewing : number;
  Puntadas : number;
  ManejoPaquete: string;
  Rate: number;
  JornadaLaboral: number;
  IdTela: number;
  Onza: number;
  MateriaPrima_1: string;
  MateriaPrima_2 : string;
  MateriaPrima_3 : string;
  MateriaPrima_4 : string;
  MateriaPrima_5 : string;
  MateriaPrima_6 : string;
  MateriaPrima_7 : string;
  Familia : string;
  TipoConstruccion : string;
  FechaRegistro : Date;
  IdUsuario : number;
  Usuario : string;
  FactorSewing : number;
  FactorSewingAccuracy : number;
  Tmus_Mac : number;
  Tmus_MinL : number;
  Min_Mac : number;
  Min_NML : number;
  Min_Mac_CC : number;
  Min_NML_CC : number;
  Sam : number;
  ProducJL : number;
  Precio : number;
  IdUsuarioModifica : number;
  UsuarioModifica : string;
  FechaModifica : Date;
  }
